#!/usr/bin/env python3
"""Regenerate config/native_decomp_sources.txt from src/**/*.cpp SKIP_ASM bodies."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT = ROOT / "config" / "native_decomp_sources.txt"

# Always linked: core utilities + boot/runtime + first-wave game decomp.
BASE = [
    "src/hashvalue.cpp",
    "src/md5.cpp",
    "src/bxrandom.cpp",
    "src/mem/operator_new.cpp",
    "src/dirtysock/tags.cpp",
    "src/visualfx/crowdrender2d.cpp",
    "src/bx/bigfile.cpp",
    "src/main/ssxapp_port.cpp",
    "src/fe/cfelocale_port.cpp",
    "src/input/inputmap.cpp",
    "src/input/inputpad.cpp",
    "src/object/movenode.cpp",
    "src/object/movenode_helpers.cpp",
    "src/object/listnode.cpp",
    "src/object/bucketman.cpp",
    "src/object/bucketpurge.cpp",
    "src/object/spline3d.cpp",
    "src/fe/cfestate_title.cpp",
    "src/fe/cfestate_mainmenu.cpp",
    "src/fe/cfestate_mountainroom.cpp",
    "src/fe/cfestate_options.cpp",
    "src/fe/cfestate_options_game.cpp",
    "src/fe/cfestate_options_sound.cpp",
    "src/fe/cfestate_options_controller.cpp",
    "src/fe/cfestate_options_saveload.cpp",
    "src/fe/cfestate_online_mainmenu.cpp",
    "src/fe/cfestate_transition.cpp",
    "src/fe/cfestate_bonus_material.cpp",
    "src/fe/cfestate_multimode.cpp",
    "src/fe/cfestate_event_select.cpp",
    "src/fe/cfestate_peak_room.cpp",
    "src/ui/uiengine_port.cpp",
    "src/world/world_native.cpp",
    "src/main/main_native.cpp",
    "src/main/game_native.cpp",
    "src/main/game_mode_native.cpp",
    "src/main/section_native.cpp",
    "src/ai/rider.cpp",
    "src/ai/cai.cpp",
    "src/ai/airpredictor.cpp",
    "src/dcd10/cAppMan.cpp",
    "src/dcd10/cAppMan_mainLoop.cpp",
    "src/retail/boot_runtime.cpp",
    "src/retail/retail_memset.cpp",
    "src/retail/synctask_retail_impl.cpp",
    "src/retail/synctask_pool.cpp",
]

SKIP_SCAN = set(BASE)


def has_skip_asm_body(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    if "#ifdef SKIP_ASM" not in text:
        return False
    pos = 0
    while True:
        start = text.find("#ifdef SKIP_ASM", pos)
        if start < 0:
            break
        i = start + len("#ifdef SKIP_ASM")
        depth = 1
        while depth > 0:
            m = re.search(r"#(ifdef|ifndef|if|else|elif|endif)\b", text[i:])
            if not m:
                return False
            if m.group(1) == "endif":
                depth -= 1
            elif m.group(1) in ("ifdef", "ifndef", "if"):
                depth += 1
            i += m.end()
        block = text[start + len("#ifdef SKIP_ASM") : i - len("#endif")]
        stripped = re.sub(r"//.*?$|/\*.*?\*/", "", block, flags=re.MULTILINE | re.DOTALL).strip()
        if len(stripped) > 40:
            return True
        pos = i
    return False


def main() -> int:
    discovered: list[str] = []
    for cpp in sorted(SRC.rglob("*.cpp")):
        rel = cpp.relative_to(ROOT).as_posix()
        if rel.startswith("src/platform/linux/") or rel.startswith("src/mem/units/"):
            continue
        if rel in SKIP_SCAN:
            continue
        if has_skip_asm_body(cpp):
            discovered.append(rel)

    lines = sorted(set(BASE + discovered))
    header = (
        "# Auto-generated by scripts/sync_native_decomp.py — do not edit by hand.\n"
        "# Re-run after adding SKIP_ASM bodies, then: python configure.py && ninja native\n"
    )
    OUT.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"[native-decomp] {len(lines)} source(s) → {OUT.relative_to(ROOT)}")
    for line in lines:
        print(f"  {line}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
